In [1]:
import psycopg2

In [2]:
conn=psycopg2.connect(database="Course_data",
                      user="postgres",
                      password="rohini28")

In [3]:
crsr=conn.cursor()

In [27]:
crsr.execute("select * from employees where department ='Sports'")

In [28]:
crsr.fetchall()

[(1,
  'Berrie',
  'Manueau',
  'bmanueau0@dion.ne.jp',
  datetime.date(2006, 4, 20),
  'Sports',
  'F',
  154864,
  4),
 (6,
  'Bethena',
  'Trow',
  'btrow5@technorati.com',
  datetime.date(2003, 6, 8),
  'Sports',
  'F',
  134501,
  3),
 (34,
  'Lucy',
  'Olifaunt',
  'lolifauntx@dailymotion.com',
  datetime.date(2005, 2, 7),
  'Sports',
  'F',
  165660,
  7),
 (51,
  'Norine',
  'Steinham',
  None,
  datetime.date(2008, 8, 22),
  'Sports',
  'F',
  66488,
  2),
 (77,
  'Maurice',
  'Philbrick',
  None,
  datetime.date(2006, 1, 8),
  'Sports',
  'M',
  67615,
  1),
 (89,
  'Claudetta',
  'Sappson',
  'csappson2g@aboutads.info',
  datetime.date(2011, 8, 24),
  'Sports',
  'F',
  157802,
  5),
 (156,
  'Joleen',
  'Rothwell',
  'jrothwell4b@fastcompany.com',
  datetime.date(2004, 10, 24),
  'Sports',
  'F',
  29838,
  2),
 (164,
  'Benjamin',
  'Younie',
  'byounie4j@cdbaby.com',
  datetime.date(2006, 11, 13),
  'Sports',
  'M',
  21735,
  2),
 (190,
  'Averyl',
  'Weinmann',
  'aweinmann59@google.com.au',
  datetime.date(2014, 10, 12),
  'Sports',
  'F',
  118250,
  7),
 (191,
  'Marjorie',
  'Leavey',
  'mleavey5a@myspace.com',
  datetime.date(2012, 8, 17),
  'Sports',
  'F',
  130147,
  5),
 (206,
  'Cyndi',
  'Danilchenko',
  None,
  datetime.date(2008, 5, 29),
  'Sports',
  'F',
  71364,
  1),
 (211,
  'Michail',
  'Leamy',
  'mleamy5u@ted.com',
  datetime.date(2011, 3, 7),
  'Sports',
  'M',
  103760,
  6),
 (337,
  'Eden',
  'Instock',
  'einstock9c@seattletimes.com',
  datetime.date(2010, 11, 28),
  'Sports',
  'F',
  30836,
  1),
 (398,
  'Gustavo',
  'Jollands',
  'gjollandsb1@constantcontact.com',
  datetime.date(2014, 3, 1),
  'Sports',
  'M',
  77085,
  3),
 (423,
  'Gav',
  'Cohn',
  None,
  datetime.date(2008, 7, 18),
  'Sports',
  'M',
  115978,
  3),
 (461,
  'Stefano',
  'Greener',
  'sgreenercs@bbc.co.uk',
  datetime.date(2015, 5, 16),
  'Sports',
  'M',
  61867,
  7),
 (474,
  'Bryna',
  'Rops',
  'bropsd5@amazon.com',
  datetime.date(2011, 4, 18),
  'Sports',
  'F',
  30762,
  1),
 (502,
  'Darbie',
  'Morando',
  'dmorandodx@bizjournals.com',
  datetime.date(2015, 10, 24),
  'Sports',
  'F',
  98668,
  4),
 (524,
  'Esme',
  'Gostick',
  'egostickej@hugedomains.com',
  datetime.date(2003, 8, 2),
  'Sports',
  'M',
  51318,
  5),
 (540,
  'Cody',
  'Stodit',
  'cstoditez@thetimes.co.uk',
  datetime.date(2003, 10, 5),
  'Sports',
  'M',
  87813,
  1),
 (543,
  'Sherwynd',
  'Shelliday',
  'sshellidayf2@t-online.de',
  datetime.date(2010, 9, 19),
  'Sports',
  'M',
  164470,
  3),
 (555,
  'Andra',
  'Saile',
  'asailefe@indiatimes.com',
  datetime.date(2003, 6, 21),
  'Sports',
  'F',
  150195,
  6),
 (573,
  'Nan',
  'Ellerman',
  'nellermanfw@odnoklassniki.ru',
  datetime.date(2009, 8, 6),
  'Sports',
  'F',
  28029,
  1),
 (598,
  'Darrin',
  'Bellino',
  'dbellinogl@springer.com',
  datetime.date(2004, 1, 17),
  'Sports',
  'M',
  142943,
  6),
 (636,
  'Adam',
  'Fenwick',
  'afenwickhn@whitehouse.gov',
  datetime.date(2015, 9, 15),
  'Sports',
  'M',
  67057,
  3),
 (666,
  'Dreddy',
  'Lettley',
  'dlettleyih@smh.com.au',
  datetime.date(2015, 10, 28),
  'Sports',
  'F',
  38793,
  4),
 (752,
  'Melita',
  'Higgonet',
  'mhiggonetkv@tripadvisor.com',
  datetime.date(2006, 9, 17),
  'Sports',
  'F',
  136922,
  4),
 (784,
  'Starlin',
  'McConachie',
  'smcconachielr@so-net.ne.jp',
  datetime.date(2004, 9, 7),
  'Sports',
  'F',
  38120,
  1),
 (832,
  'Monique',
  'Ivanovic',
  'mivanovicn3@desdev.cn',
  datetime.date(2016, 6, 13),
  'Sports',
  'F',
  150061,
  1),
 (846,
  'Stanley',
  'Brecknell',
  None,
  datetime.date(2009, 11, 17),
  'Sports',
  'M',
  151814,
  4),
 (847,
  'Gweneth',
  'MacCrann',
  None,
  datetime.date(2014, 9, 12),
  'Sports',
  'F',
  29047,
  7),
 (924,
  'Lynn',
  'Housen',
  'lhousenpn@dot.gov',
  datetime.date(2015, 9, 3),
  'Sports',
  'F',
  46529,
  5),
 (979,
  'Delila',
  'Ambrogi',
  'dambrogir6@diigo.com',
  datetime.date(2007, 6, 30),
  'Sports',
  'F',
  27064,
  6),
 (991,
  'Marquita',
  'Seawell',
  'mseawellri@technorati.com',
  datetime.date(2014, 9, 7),
  'Sports',
  'F',
  38909,
  4)]

In [31]:
crsr.close()

In [32]:
conn.close()

In [34]:
conn=psycopg2.connect(database="Course_data",
                      user="postgres",
                      password="rohini28")

In [40]:
cur=conn.cursor()

In [41]:
cur.execute("select * from departments")

In [42]:
cur.fetchall()

[('Clothing', 'Home'),
 ('Grocery', 'Home'),
 ('Decor', 'Home'),
 ('Furniture', 'Home'),
 ('Computers', 'Electronics'),
 ('Device Repair', 'Electronics'),
 ('Phones & Tablets', 'Electronics'),
 ('Garden', 'Outdoors'),
 ('Camping & Fishing', 'Outdoors'),
 ('Sports', 'Outdoors'),
 ('Children Clothing', 'Kids'),
 ('Toys', 'Kids'),
 ('Vitamins', 'Health'),
 ('Pharmacy', 'Health'),
 ('First Aid', 'Health'),
 ('Automotive', 'Hardware'),
 ('Tools', 'Hardware'),
 ('Jewelry', 'Fashion'),
 ('Beauty', 'Fashion'),
 ('Cosmetics', 'Fashion'),
 ('Books', 'Entertainment'),
 ('Games', 'Entertainment'),
 ('Music', 'Entertainment'),
 ('Movies', 'Entertainment')]